config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: :registrations
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :transactions do
    collection { get :chart_and_new_transaction_data }
  end

  resources :categories do
    collection { post :sort }
  end

  resources :pricing_plans, only: [:index] do
    member do
      get 'checkout'
      post 'upgrade_with_stripe'
      get 'paypal_express_checkout'
      get 'upgrade_with_paypal'
      get 'cancel_payment'
      get 'downgrade'
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'users/registrations' }

  resources :home, only: [:index] do
    collection { post :send_contact_us }
  end

  root 'home#index'
end

app/models/pricing_plan.rb
class PricingPlan < ActiveRecord::Base
  has_many :users

  with_options presence: true do |p|
    p.validates :name, length: { maximum: 255 }
    p.validates :price, numericality: { greater_than_or_equal_to: 0.0 }
    p.validates :quantity_of_categories, numericality: { greater_than: 0, only_integer: true }
    p.validates :quantity_of_transactions, numericality: { greater_than: 0, only_integer: true }
  end

  # def self.defaul_plan
  #   self.find_by_name("mini")
  # end

  # def method_missing(meth, *args, &block)
  #   method_name = meth.to_s.gsub("?","")
  #   if method_name.in?(PricingPlan.pluck(:name))
  #     self.class.send('define_method', meth) {
  #       method_name == self.name
  #     }
  #     self.send(meth)
  #   else
  #     super
  #   end
  # end
end

app/controllers/pricing_plans_controller.rb
class PricingPlansController < ApplicationController
  before_action :set_pricing_plan, only: [:checkout, :upgrade_with_stripe, :paypal_express_checkout, :cancel_payment]

  def index
    @pricing_plans = PricingPlan.all
  end

  def checkout
  end

  def upgrade_with_stripe
    begin
      current_user.create_stripe_customer(params[:stripeToken]) if current_user.stripe_id.blank?
      current_user.pay_via_stripe!(@pricing_plan)
      finish_payment
    rescue Stripe::CardError => e
      redirect_to cancel_paypal_pricing_plan_path(id: params[:id], message: e.message)
    end
  end

  def paypal_express_checkout
    amount = (@pricing_plan.price * 100).to_i

    response = EXPRESS_GATEWAY.setup_purchase(amount,
      ip: request.remote_ip,
      return_url: upgrade_with_paypal_pricing_plan_url(@pricing_plan),
      cancel_return_url: cancel_payment_pricing_plan_url(@pricing_plan),
      currency: Figaro.env.currency_code,
      allow_guest_checkout: true,
      items: [{name: @pricing_plan.name, description: "Payment for pricing plan ##{ @pricing_plan.name }", quantity: "1", amount: amount}]
    )
    redirect_to EXPRESS_GATEWAY.redirect_url_for(response.token)

  end

  def upgrade_with_paypal
    purchase = current_user.pay_via_paypal!( params.merge({ ip: request.remote_ip }) )
    if purchase[:success]
      finish_payment
    else
      redirect_to cancel_payment_pricing_plan_path(id: purchase[:id], message: purchase[:message])
    end
  end

  def cancel_payment
    # TODO: test with invalid response
    flash[:error] = params[:message] || response.message
    redirect_to checkout_pricing_plan_path(@pricing_plan)
  end

  def finish_payment
    flash[:success] = "You Pricing plan was successfully upgrated. Congrates with #{ current_user.pricing_plan.name.capitalize } pricing plan!"
    redirect_to root_path
  end

  def downgrade
    if current_user.can_downgrade?(params[:id])
      current_user.send(:set_pricing_plan, params[:id])
      flash[:success] = "You Pricing plan was successfully downgrated to #{ current_user.pricing_plan.name.capitalize } pricing plan!"
    else
      flash[:error] = "You don't have permissions to upgrade pricing plan"
    end
    redirect_to root_path
  end

  private
  def set_pricing_plan
    @pricing_plan = PricingPlan.find(params[:id])
  end
end

app/views/pricing_plans/checkout.html.haml
.pricing-plan-container
  .pricing-row
    %h3
      Pricing plan
      %span.highlight #{@pricing_plan.name.capitalize}
  .pricing-plan-price
    %p
      %span.highlight
        %br
        = "#{@pricing_plan.price} #{Figaro.env.currency_code}"
        %br
      per transaction
  .pricing-row
    %h3
      - if @pricing_plan.premium?
        Unlimate categories
      - else
        #{@pricing_plan.quantity_of_categories} categories
  .pricing-row
    %h3
      - if @pricing_plan.premium?
        Unlimate transactions
      - else
        #{@pricing_plan.quantity_of_transactions} transactions

.payment-methods
  %h5 Select payment method

  = link_to paypal_express_checkout_pricing_plan_path(@pricing_plan) do
    = image_tag "paypal.jpg"
  = form_tag upgrade_with_stripe_pricing_plan_path, { method: :post, id: 'stripe_form' } do
    %noscript
      You must
      = link_to "enable JavaScript", "http://www.enable-javascript.com", :target => "_blank"
      in your web browser in order to pay via Stripe.
    = hidden_field_tag :id, @pricing_plan.id
    %button#stripe_button{ :'data-amount'      => (@pricing_plan.price*100).to_i,
                           :'data-image'       => "/assets/coin-logo.jpg",
                           :'color'            => 'black',
                           :'data-currency'    => Figaro.env.currency_code,
                           :'data-description' => "Payment for pricing plan ##{ @pricing_plan.name }",
                           :'data-key'         => Figaro.env.stripe_publishable_key,
                           :'data-email'       => current_user.email,
                           :'data-name'        => 'Save Budget',
                           :type               => "submit"}
      = image_tag "stripe.png"
    %script{:src => "https://checkout.stripe.com/v2/checkout.js"}

app/views/pricing_plans/index.html.haml
.header
  %h2 Pick your plan
  %h4 Upgrade, downgrade, or cancel anytime.
  %p.another-design in another design
.row.pricing-wrapper
  - @pricing_plans.each do |pricing_plan|
    .col-md-3.col-lg-3.col-xs-6.col-sm-6.column
      %div{ class: "pricing-table hover recommended #{ pricing_plan.name}" }
        %h1.pricing-title=pricing_plan.name
        .border.rotate
          .table-price
            = number_to_currency pricing_plan.price
            %span= "/mo"
        %ul.list-group
          %li.list-group-item
            - if pricing_plan.premium?
              Unlimate
            - else
              #{pricing_plan.quantity_of_categories} categories
          %li.list-group-item
            - if pricing_plan.premium?
              Unlimate
            - else
              #{pricing_plan.quantity_of_transactions} transactions
        .table-buy
          - unless pricing_plan.name.eql?(current_user.pricing_plan.name)
            - if pricing_plan.price < current_user.pricing_plan.price
              = link_to "Downgrade", downgrade_pricing_plan_path(pricing_plan), class: 'primary-action stretch_two'
            - else
              = link_to "Buy now", checkout_pricing_plan_path(pricing_plan), class: 'primary-action stretch_two'

.row.pricing-wrapper2.hidden
  - @pricing_plans.each do |pricing_plan|
    .col-md-3.col-sm-6.col-xs-10.col-xs-offset-1.col-sm-offset-0
      %div{ class: "pinpong-item another-#{ pricing_plan.name}" }
        .pinpong-header
          .figure
            .sanimate{ "data-path-hover" => "m 0.2375,-1.325 0,118.2 c 46.5,-14.6 60.5,-21.4 97.5,-21.2 37,0.2 49.6,5.5 97.5,19.4 l 0,-118.2 -195,1.8 z" }
              .height-figure
              %svg{:preserveAspectRatio => "none", :viewBox => "0 0 178 610"}
                %path{:d => "m 0,0 0,171.14385 c 24.580441,15.47138 55.897012,24.75772 90,24.75772 34.10299,0 65.41956,-9.28634 90,-24.75772 L 180,0 0,0 z"}/
              .figcaption
                %h2.whitetext.bold= pricing_plan.name.capitalize
                .pinpong-body
                  .pinpong-price
                    .post
                      .roboto.medium.top
                        %span.dollersi $
                        = pricing_plan.price
                        %span Month
                  .details
                    %ul.blbord
                      - if pricing_plan.premium?
                        %li
                          %strong Unlimate
                        %li
                          %strong Unlimate
                      - else
                        %li
                          %strong= pricing_plan.quantity_of_categories
                          Categories
                        %li
                          %strong= pricing_plan.quantity_of_transactions
                          Transactions
                .pinpong-footer
                  - unless pricing_plan.name.eql?(current_user.pricing_plan.name)
                    - if pricing_plan.price < current_user.pricing_plan.price
                      = link_to "Downgrade", downgrade_pricing_plan_path(pricing_plan), class: 'btn svbutton bold'
                    - else
                      = link_to "Buy now", checkout_pricing_plan_path(pricing_plan), class: 'btn svbutton bold'