config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: :registrations
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :transactions do
    collection { get :chart_and_new_transaction_data }
  end

  resources :categories do
    collection { post :sort }
  end

  resources :pricing_plans, only: [:index] do
    member do
      get 'checkout'
      post 'upgrade_with_stripe'
      get 'paypal_express_checkout'
      get 'upgrade_with_paypal'
      get 'cancel_payment'
      get 'downgrade'
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'users/registrations' }

  resources :home, only: [:index] do
    collection { post :send_contact_us }
  end

  root 'home#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user

  has_many :transactions, dependent: :restrict_with_error
  has_many :sub_categories, dependent: :destroy

  has_one :photo, as: :imageable, dependent: :destroy

  validates :name, uniqueness: { scope: :user_id }, presence: true, length: { maximum: 255 }
  # validates :user, presence: true

  default_scope -> { order('name') }

  accepts_nested_attributes_for :photo
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :destroy]
  layout 'modal', only: [:new, :edit]
  load_and_authorize_resource

  def index
    @categories = current_user.categories.page(params[:page])
  end

  def edit
  end

  def new
    @category = Category.new
  end

  def create
    @category = current_user.categories.build(category_params)
    if @category.save
      render json: { success: "Category was successfully created.", id: @category.id, name: @category.name }, status: 201, layout: 'modal'
    else
      render json: { errors: @category.errors }, status: 422
    end
  end

  def update
    if @category.update(category_params)
      render json: { success: "Category was successfully updated." , id: @category.id, name: @category.name }, status: 200, layout: 'modal'
    else
      render json: { errors: @category.errors }, status: 422
    end
  end

  def destroy
    if @category.destroy
      render json: { success: "Category was successfully destroyed." }, status: 200
    else
      render json: { error: @category.errors.full_messages.to_sentence }, status: 422
    end
  end

  def sort
    params[:category].each_with_index do |id, index|
      Category.find(id).update_column :position, index+1
    end
    render nothing: true
  end

  private
    def set_category
      @category = current_user.categories.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :user_id)
    end
end

app/views/categories/_category.html.haml
= content_tag_for :li, category, class: "ui-state-default"  do
  %span.ui-icon.ui-icon-arrowthick-2-n-s
  .category-name= category.name
  = link_to category_path(category, format: :json), class: 'category_action delete-category-js' do
    .glyphicon.glyphicon-remove
  = link_to edit_category_path(category.id), data: { :'remote-target' => '#categories-form .modal-content' }, class: 'open-category-js category_action', title: 'Edit' do
    .glyphicon.glyphicon-pencil

app/views/categories/_form.html.haml
.modal-header
  %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
  %h4.modal-title
    = @category.new_record? ? 'New' : 'Edit'
    %span.semi-bold Category

= form_for @category, html: { class: 'form-horizontal' } do |f|
  .modal-body
    #error_explanation
    .form-group
      = f.label :name, class: 'col-sm-3 control-label'
      .col-sm-5
        = f.text_field :name, class: 'form-control'

  .modal-footer
    .pull-right
      = f.submit "Submit", class: 'btn btn-default'

app/views/categories/edit.html.haml
= render 'form'

app/views/categories/index.html.haml
- if cannot? :create, Category
  .center.alert.fade.in.alert-info
    %button.close{"data-dismiss" => "alert"}×
    You cann't create more then #{current_user.pricing_plan.quantity_of_categories} categories on #{current_user.pricing_plan.name.capitalize} pricing plan.
    Please upgrade your #{ link_to "Pricing plan", pricing_plans_path }

%h1 Categories
.col-sm-offset-2
  = paginate @categories
%ul#sortable{ "data-update-url" => sort_categories_url }
  = render partial: "category", collection: @categories
  - if @categories.blank?
    %li.ui-state-default.text-center
      = 'No categories'

- if can? :create, Category
  .col-md-12
    %br
      = link_to 'New Category', new_category_path, data: { :'remote-target' => '#categories-form .modal-content' }, class: 'open-category-js', title: "New"

= content_for :overlay do
  = render "overlays/categories/form"

app/views/categories/new.html.haml
= render 'form'