config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: :registrations
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :transactions do
    collection { get :chart_and_new_transaction_data }
  end

  resources :categories do
    collection { post :sort }
  end

  resources :pricing_plans, only: [:index] do
    member do
      get 'checkout'
      post 'upgrade_with_stripe'
      get 'paypal_express_checkout'
      get 'upgrade_with_paypal'
      get 'cancel_payment'
      get 'downgrade'
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'users/registrations' }

  resources :home, only: [:index] do
    collection { post :send_contact_us }
  end

  root 'home#index'
end

app/views/layouts/_navbar.html.haml
.navbar-header
  %button.navbar-toggle.collapsed{"aria-expanded": "false", "data-target": "#bs-example-navbar-collapse-1", "data-toggle": "collapse", type: "button"}
    %span.sr-only Toggle navigation
    %span.icon-bar
    %span.icon-bar
    %span.icon-bar
  = link_to "SaveBudget", root_path, class: 'navbar-brand'
.collapse.navbar-collapse
  %ul.nav.navbar-nav
    %li{ class: "#{ 'active' if categories_active?}" }= link_to "Categories", categories_path
    %li{ class: "#{ 'active' if transactions_active?}" }= link_to "Transactions", transactions_path
    %li{ class: "#{ 'active' if pricing_plans_active?}" }= link_to "Pricing Plans", pricing_plans_path
  = render 'layouts/user_dropdown'

app/views/layouts/_user_dropdown.html.haml
%ul.nav.navbar-nav.navbar-right
  %li.dropdown
    = link_to "#", class: "dropdown-toggle user-dropdown", "aria-expanded": "false", "aria-haspopup": "true", "data-toggle":"dropdown", role: "button" do
      .row
        .col-xs-3
          - if current_user.photo.try(:id)
            = image_tag current_user.photo.file_url(:small), class: 'pull-left img-rounded'
          - else
            = image_tag "", class: 'profile-pic media-object pull-left img-rounded', "data-name": current_user.first_name
        .col-xs-9
          = current_user.full_name
          %br
          %small= current_user.email
          %span.caret
    %ul.dropdown-menu
      %li
        = link_to "Show profile", edit_user_registration_path
      %li
        = link_to "Sign out", destroy_user_session_path, method: :delete

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Budget
    = include_gon
    = stylesheet_link_tag    'application', media: 'all'
    = csrf_meta_tags
  %body{ body_attributes }
    - if user_signed_in?
      %nav.navbar.navbar-default
        .container-fluid
          = render 'layouts/navbar'

    .container
      #flash_message
        - flash.each do |name, msg|
          %div{ class: "center alert fade in alert-#{ name }" }
            %button.close{ "data-dismiss" => "alert" }×
            = content_tag :div, msg, id: "flash_#{name}"
      = yield
  = javascript_include_tag 'application'
  = yield :overlay

app/views/layouts/dashboard.html.haml
!!!
%html
  %head
    %title Budget
    = include_gon
    = stylesheet_link_tag 'application', media: 'all'
    = csrf_meta_tags
  %body{ body_attributes }
    %header#header
      %nav.navbar.navbar-fixed-top{:role => "banner"}
        .container
          .navbar-header
            %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
              %span.sr-only Toggle navigation
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            = link_to "SaveBudget", root_path, class: "navbar-brand"
          .collapse.navbar-collapse.navbar-right
            %ul.nav.navbar-nav
              %li.active
                = link_to "Home", "#header"
              %li
                = link_to "Feature", "#feature"
              %li
                = link_to "Gallery", "#gallery"
              %li
                = link_to "Price & Plan", "#pricing"
              %li
                = link_to "Our Team", "#our-team"
              %li
                = link_to "Contact", "#contact"

            - if current_user
              = render 'layouts/user_dropdown'
        / /.container
      .container
        #flash_message
          - flash.each do |name, msg|
            %div{ class: "center alert fade in alert-#{ name }" }
              %button.close{ "data-dismiss" => "alert" }×
              = content_tag :div, msg, id: "flash_#{name}"
      / /nav
    / /header
    = yield
  = javascript_include_tag 'application'

app/views/layouts/devise.html.haml
!!!
%html
  %head
    %title Budget
    = stylesheet_link_tag    'application', media: 'all'
    = csrf_meta_tags
  %body{ body_attributes }
    .container
      #flash_message
        .center.alert.fade.in.alert-danger
          %button.close{ "data-dismiss" => "alert" }×
          - flash.each do |name, msg|
            = content_tag :div, msg, id: "flash_#{name}"
      = yield
  = javascript_include_tag 'application'

app/views/layouts/modal.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no", :name => "viewport"}/
    = include_gon
  %body{ body_attributes }
    = yield